global:
  domain: argo.mhlyva.sid24.xyz

configs:
  params:
    server.insecure: true
  credentialTemplates:
    ssh-creds:
      url: git@github.com:maksym-zok/Lesson_11_CI_CD_practice.git
      sshPrivateKey: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        -----END OPENSSH PRIVATE KEY-----
  repositories:
    devops-course:
      url: git@github.com:maksym-zok/Lesson_11_CI_CD_practice.git
server:
  ingress:
    enabled: true
    controller: aws
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/certificate-arn: 'arn:aws:acm:eu-central-1:637423460784:certificate/1e6bb41c-5fcd-4d00-b4ec-ffa765aa7eb8'
    aws:
      serviceType: ClusterIP
      backendProtocolVersion: GRPC
