apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app_name }}
type: Opaque
data:
  JWT_SECRET: dGhpc2lzYXNlY3JldGtleQo=
  SMTP_USERNAME: ZW1haWwtc2VydmVyLXVzZXJuYW1lCg==
  SMTP_PASSWORD: ZW1haWwtc2VydmVyLXBhc3N3b3JkCg==