apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.app_name }}
  sessionAffinity: "ClientIP"
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.app_port }}