apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-hello
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-hello
        image: nginxdemos/hello
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80